# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitWip < Formula
  desc ""
  homepage ""
  version "0.0.1"

  on_macos do
    on_intel do
      url "https://github.com/carhartl/git-wip/releases/download/v0.0.1/git-wip_0.0.1_darwin_amd64.tar.gz"
      sha256 "a8e09f1fffa05e07d2227ee652e9cc8932bb470b18e99e3366534ca80a8b0dd0"

      def install
        bin.install "git-wip"
      end
    end
    on_arm do
      url "https://github.com/carhartl/git-wip/releases/download/v0.0.1/git-wip_0.0.1_darwin_arm64.tar.gz"
      sha256 "11e8be97f61604f627ad100d873f1a10fc39a7157d4556eab37363d85a23132a"

      def install
        bin.install "git-wip"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/carhartl/git-wip/releases/download/v0.0.1/git-wip_0.0.1_linux_amd64.tar.gz"
        sha256 "91c10f93d2a8f3735b5563ebd22427a96b7234d07698350994eecbf985dd0a62"

        def install
          bin.install "git-wip"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/carhartl/git-wip/releases/download/v0.0.1/git-wip_0.0.1_linux_arm64.tar.gz"
        sha256 "35d6b28d1a4ff22591b37593bc5d447205b7b04eedcc2000b572263026e319ea"

        def install
          bin.install "git-wip"
        end
      end
    end
  end
end
