# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitWip < Formula
  desc ""
  homepage ""
  version "0.0.6"

  on_macos do
    on_intel do
      url "https://github.com/carhartl/git-wip/releases/download/v0.0.6/git-wip_0.0.6_darwin_amd64.tar.gz"
      sha256 "755f58be9be99eaa62ef93a9bcaa4302f3058275d8c78e6fdb1c1b1fddb5e429"

      def install
        bin.install "git-wip"
      end
    end
    on_arm do
      url "https://github.com/carhartl/git-wip/releases/download/v0.0.6/git-wip_0.0.6_darwin_arm64.tar.gz"
      sha256 "e24449db0f69090ee70f3f11b97ab631afb166b4c4804e8eb90ab14874ce475c"

      def install
        bin.install "git-wip"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/carhartl/git-wip/releases/download/v0.0.6/git-wip_0.0.6_linux_amd64.tar.gz"
        sha256 "68d635173e2538a563de730ed8defac6a4c14f359ba02a5d186dfcb172ac95ee"

        def install
          bin.install "git-wip"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/carhartl/git-wip/releases/download/v0.0.6/git-wip_0.0.6_linux_arm64.tar.gz"
        sha256 "b6acbfdb7752af3348fdd31d5e85628e8deb5fb408cb1f0a2074b6ad20794172"

        def install
          bin.install "git-wip"
        end
      end
    end
  end
end
