# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitCommitTemplate < Formula
  desc ""
  homepage ""
  version "0.0.1"

  depends_on "git"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/carhartl/git-commit-template/releases/download/v0.0.1/git-commit-template_0.0.1_darwin_arm64.tar.gz"
      sha256 "3b48d2476354372546430b1ad6a49741b0553c2f63ea36057027d1b3c7836378"

      def install
        bin.install "git-commit-template"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/carhartl/git-commit-template/releases/download/v0.0.1/git-commit-template_0.0.1_darwin_amd64.tar.gz"
      sha256 "99bc989a747cfd2afbf3c0e8a08bef79803e5c4e9322c079eaf57a6fdc5570bd"

      def install
        bin.install "git-commit-template"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/carhartl/git-commit-template/releases/download/v0.0.1/git-commit-template_0.0.1_linux_arm64.tar.gz"
      sha256 "f73c6dcf929890524172fd81ad15933f91f2b6c76391d09f6ff02eca431322f5"

      def install
        bin.install "git-commit-template"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/carhartl/git-commit-template/releases/download/v0.0.1/git-commit-template_0.0.1_linux_amd64.tar.gz"
      sha256 "dd1009295e29bce70b022d3ea9cecf91668ad42bcf1ca8666c505bf83f43d0fd"

      def install
        bin.install "git-commit-template"
      end
    end
  end
end
