# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitWip < Formula
  desc ""
  homepage ""
  version "0.0.4"

  on_macos do
    on_intel do
      url "https://github.com/carhartl/git-wip/releases/download/v0.0.4/git-wip_0.0.4_darwin_amd64.tar.gz"
      sha256 "bc65e09eac8e89c71812003dc1d2e34d605f844c502add33fe58e02020ea2f71"

      def install
        bin.install "git-wip"
      end
    end
    on_arm do
      url "https://github.com/carhartl/git-wip/releases/download/v0.0.4/git-wip_0.0.4_darwin_arm64.tar.gz"
      sha256 "ea483cada413bd48402b8646332667ed7653c3790747b75bcdaefbc591ae0067"

      def install
        bin.install "git-wip"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/carhartl/git-wip/releases/download/v0.0.4/git-wip_0.0.4_linux_amd64.tar.gz"
        sha256 "0090a8e7c5fc3bb212be9b1c72d8ebc39663babafd83285452d4f12f24370a20"

        def install
          bin.install "git-wip"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/carhartl/git-wip/releases/download/v0.0.4/git-wip_0.0.4_linux_arm64.tar.gz"
        sha256 "936d33c5db93cee26e3fc7ac02d4ebdfa43eb98c992c59f4a91d13b905b7089c"

        def install
          bin.install "git-wip"
        end
      end
    end
  end
end
