# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitCommitTemplate < Formula
  desc ""
  homepage ""
  version "0.1.1"

  depends_on "git"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/carhartl/git-commit-template/releases/download/v0.1.1/git-commit-template_0.1.1_darwin_arm64.tar.gz"
      sha256 "1d54710b02cdfdf584233b3c585381ecb92f6ff6396e949b92ad3da2ec139e11"

      def install
        bin.install "git-commit-template"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/carhartl/git-commit-template/releases/download/v0.1.1/git-commit-template_0.1.1_darwin_amd64.tar.gz"
      sha256 "f9becae7c984e457343120e4ea4ba9d7399ccb8b189ec1831296f093a9a5007e"

      def install
        bin.install "git-commit-template"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/carhartl/git-commit-template/releases/download/v0.1.1/git-commit-template_0.1.1_linux_arm64.tar.gz"
      sha256 "a7f4002d820924ff9162a889f4958c9c9cd3172033843404cc1a065a3bd08ea8"

      def install
        bin.install "git-commit-template"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/carhartl/git-commit-template/releases/download/v0.1.1/git-commit-template_0.1.1_linux_amd64.tar.gz"
      sha256 "fee88a197f0a239a57887d110d94d14ff9519378b1d26423e687dfc91d075518"

      def install
        bin.install "git-commit-template"
      end
    end
  end
end
